# -*- coding: utf-8 -*-
#
# SixEye API Documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.todo']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
copyright = u'2022 SixEye Ltd'
author = u'SixEye Ltd'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'1.0'
# The full version, including alpha/beta/rc tags.
release = u'1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Exclude warnings about documents not included in toctree
suppress_warnings = ['toc.excluded']


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
#
html_theme = 'furo'
html_title = 'SixEye API'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_footer_icons = [
    {
        "name": "SixEye",
        "url": "https://www.sixeye.net/",
        "html": """
            <svg stroke="currentColor" fill="#f68d2e" stroke-width="0" viewBox="0 0 16 16">
                <path fill-rule="nonzero" d="m 9.2162457,6.928194 c 0,0.6717632 -0.5444614,1.2166125 -1.2161656,1.2166125 -0.6715945,0 -1.2163258,-0.5448493 -1.2163258,-1.2166125 0,-0.6714343 0.5447313,-1.2163342 1.2163258,-1.2163342 0.6717042,0 1.2161656,0.5448999 1.2161656,1.2163342 M 8.0001392,3.2795287 c -0.6649824,0 -1.2873312,0.178226 -1.8242188,0.4888732 L 6.7839146,4.8217081 C 7.1416907,4.6148826 7.5570031,4.4954665 8.0001392,4.4954665 c 1.3431891,0 2.4324998,1.0893107 2.4324998,2.4327781 0,1.3433746 -1.0893107,2.4327781 -2.4324998,2.4327781 -1.3434675,0 -2.4327781,-1.0894035 -2.4327781,-2.4327781 H 4.3513052 c 0,2.0153656 1.6332069,3.6488934 3.648834,3.6488934 2.0152978,0 3.6487148,-1.6335278 3.6487148,-3.6488934 0,-2.0154584 -1.633417,-3.6487159 -3.6487148,-3.6487159 M 4.7024101,12.640003 H 11.297868 L 14.595926,6.9282446 11.297868,1.2164439 H 4.7024101 L 1.404352,6.9282446 Z m 7.2978279,1.216334 H 3.9998208 L 0,6.9282446 3.9998208,0 H 12.000238 L 16,6.9282446 Z"></path>
            </svg>
        """,
        "class": "",
    },
]

html_theme_options = {
    'light_logo': 'sixeye-logo.png',
    'dark_logo': 'sixeye-logo.png',
    'footer_icons': html_theme_footer_icons,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SixEyeApi'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SixeyeApi.tex', u'SixEye API',
     u'SixEye Ltd', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'sixeyeapi', u'SixEye API',
     [u'SixEye Ltd'], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SixeyeApi', u'SixEye API',
     u'SixEye Ltd', 'SixeyeApi',
     'User documentation for SixEye API.',
     'Miscellaneous'),
]
